---
- include: bootstrap.yml tags=bootstrap

- include: repo-deb.yml tags=deb,repository
  when: ansible_os_family == "Debian"

- include: repo-rpm.yml tags=rpm,repository
  when: ansible_os_family == "RedHat"

- include: pkg-deb.yml tags=deb,packages
  when: ansible_os_family == "Debian"

- include: pkg-rpm.yml tags=rpm,packages
  when: ansible_os_family == "RedHat"

- include: hostname.yml tags=hostname

- include: timezone-debian.yml tags=deb,timezone
  when: ansible_os_family == "Debian"

- include: timezone-redhat.yml tags=rpm,timezone
  when: ansible_os_family == "RedHat"

- include: ntp-deb.yml tags=ntp,deb
  when: ansible_os_family == "Debian"

- include: ntp-rpm.yml tags=ntp,rpm
  when: ansible_os_family == "RedHat"

- include: swap.yml tags=swap
  when: ansible_swaptotal_mb == 0
