---
- name: main - include bootstrap
  include: bootstrap.yml
  tags: common_bootstrap

- name: main - include repo
  include: repo.yml
  tags: common_repository

- name: main - include upgrade
  include: upgrade.yml
  when: common_upgrade
  tags: common_upgrade

- name: main - include pkg
  include: pkg.yml
  tags: common_packages

- name: main - include hostname
  include: hostname.yml
  tags: common_hostname

- name: main - include timezone
  include: timezone.yml
  tags: common_timezone

- name: main - include ntp
  include: ntp.yml
  tags: common_ntp

- name: main - include filesystems
  include: filesystems.yml
  when: common_filesystems is defined and common_filesystems != []
  tags: common_filesystems

- name: main - include swap
  include: swap.yml
  when: common_swap
  tags: common_swap

- meta: flush_handlers

- name: main - regather facts
  action: setup

