---
- include: bootstrap.yml
  tags: common_bootstrap

- include: repo-deb.yml
  when: ansible_os_family == "Debian"
  tags: common_repository

- include: repo-rpm.yml
  when: ansible_os_family == "RedHat"
  tags: common_repository

- include: upgrade.yml
  when: ansible_os_family == "Debian" and common_upgrade
  tags: common_upgrade

- include: pkg-deb.yml
  when: ansible_os_family == "Debian"
  tags: common_packages

- include: pkg-rpm.yml
  when: ansible_os_family == "RedHat"
  tags: common_packages

- include: hostname.yml
  tags: common_hostname

- include: timezone-debian.yml
  when: ansible_os_family == "Debian"
  tags: common_timezone

- include: timezone-redhat.yml
  when: ansible_os_family == "RedHat"
  tags: common_timezone

- include: ntp-deb.yml
  when: ansible_os_family == "Debian"
  tags: common_ntp

- include: ntp-rpm.yml
  when: ansible_os_family == "RedHat"
  tags: common_ntp

- include: filesystems.yml
  when: common_filesystems is defined and common_filesystems != []
  tags: common_filesystems

- include: swap.yml
  when: common_swap
  tags: common_swap

- meta: flush_handlers

- name: main - Regather facts
  action: setup

