---
- include: bootstrap.yml
  tags: common_bootstrap

- include: repo.yml
  tags: common_repository

- include: upgrade.yml
  when: common_upgrade
  tags: common_upgrade

- include: pkg.yml
  tags: common_packages

- include: hostname.yml
  tags: common_hostname

- include: timezone.yml
  tags: common_timezone

- include: ntp.yml
  tags: common_ntp

- include: filesystems.yml
  when: common_filesystems is defined and common_filesystems != []
  tags: common_filesystems

- include: swap.yml
  when: common_swap
  tags: common_swap

- meta: flush_handlers

- name: main - Regather facts
  action: setup

