---
- name: repo - Add custom repositories in Debian
  apt_repository: repo="deb {{ item.url }} {{ item.codename }} {{ item.components }}" state=present update_cache=yes
  with_items: common_repo_deb
  when: common_repo_deb is defined

- name: repo - Add custom repositories keys in Debian
  apt_key: url={{ item.url }} id={{ item.id }} state=present
  with_items: common_repo_deb_keys
  when: common_repo_deb_keys is defined
