---
- name: swap - calculate difference between existing and configured size
  set_fact:
    common_swap_check_diff: "{{ (common_swap_size | float - ansible_swaptotal_mb) | abs | int }}"
    common_swap_check_minimum_diff: "{{ common_swap_size | float * 0.10 | round(1, 'ceil') | int }}"

- name: swap - check if it is necessary to recreate it
  set_fact:
    common_swap_check_recreate: "{{ common_swap_check_diff > common_swap_check_minimum_diff }}"

- name: swap - create path
  file:
    dest: "{{ common_swap_path }}"
    owner: root
    group: root
    mode: 0600
    state: directory
  when: common_swap_check_recreate | bool
  sudo: yes

- name: swap - disable swap
  command: swapoff --all
  ignore_errors: yes
  when: common_swap_check_recreate | bool
  sudo: yes

- name: swap - create swap file
  command: dd if=/dev/zero of={{ common_swap_path }}/swap.block bs=1M count={{ common_swap_size }}
  when: common_swap_check_recreate | bool
  sudo: yes

- name: swap - make swap
  command: mkswap {{ common_swap_path }}/swap.block
  when: common_swap_check_recreate | bool
  sudo: yes

- name: swap - add to fstab
  mount:
    name: swap
    src: "{{ common_swap_path }}/swap.block"
    fstype: swap
    state: present
  when: common_swap_check_recreate | bool and common_swap_fstab
  sudo: yes

- name: swap - swap on
  command: swapon --all
  when: common_swap_check_recreate | bool
  sudo: yes

