---
- name: swap - create path
  file:
    dest: /swap
    owner: root
    group: root
    mode: 0600
    state: directory
  sudo: yes

- name: swap - create swap file
  command: dd if=/dev/zero of=/swap/swap.block bs=1M count={{ common_swap_size }}
    creates=/swap/swap.block
  sudo: yes

- name: swap - make swap
  command: mkswap /swap/swap.block
  sudo: yes

- name: swap - swap on
  command: swapon /swap/swap.block
  sudo: yes

- name: swap - add to fstab
  mount:
    name: swap
    src: /swap/swap.block
    fstype: swap
    state: present
  when: common_swap_fstab
  sudo: yes
